music_homepage:
    path:     /
    defaults: { _controller: MusicBundle:Main:index }

music_about:
    path:     /about
    defaults: { _controller: MusicBundle:Main:about }

music_news:
    path:     /news/
    defaults: { _controller: MusicBundle:Main:index, type: news }

music_release:
    path:     /releases/
    defaults: { _controller: MusicBundle:Main:index, type: release }

music_mix:
    path:     /mixes/
    defaults: { _controller: MusicBundle:Main:index, type: mix }

music_news_item:
    path:     /news/{slug}
    defaults: { _controller: MusicBundle:Main:news }

music_release_item:
    path:     /releases/{slug}
    defaults: { _controller: MusicBundle:Main:release }

music_mix_item:
    path:     /mixes/{slug}
    defaults: { _controller: MusicBundle:Main:mix }

music_play:
    path:     /play/{id}/{token}
    defaults: { _controller: MusicBundle:Media:play }

music_download:
    path:     /download/{id}/{type}
    defaults: { _controller: MusicBundle:Media:download, type: 320 }

music_order:
    path:     /order/{id}
    defaults: { _controller: MusicBundle:Payment:order }

music_order_purchase:
    path:     /order-purchase/{id}
    defaults: { _controller: MusicBundle:Payment:purchase, id: null }

music_order_duplicate:
    path: /order-duplicate
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    MusicBundle:Music:order_duplicate.html.twig